os: Windows Server 2012 R2

shallow_clone: false

version: 4.0.0.{build}

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "4.0.0."
  assembly_file_version: "{version}"
  assembly_informational_version: "{version} {APPVEYOR_REPO_COMMIT}"


clone_folder: c:\projects\resizer


install:
  - cmd: git submodule -q update --init

# build platform, i.e. x86, x64, AnyCPU. This setting is optional.
platform: 
  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  project: AppVeyor.sln      # path to Visual Studio solution or project
  publish_nuget: false             # package projects with .nuspec files and push to artifacts

  # MSBuild verbosity level
  verbosity: minimal


# scripts to run before build
before_build:
  - cd C:\projects\resizer
  - nuget restore AppVeyor.sln -PackagesDirectory C:\projects\resizer\packages

# scripts to run after build
#after_build:

# to run your custom scripts instead of automatic MSBuild
#build_script:

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

#test_script:
#  - xunit.console.clr4.exe Imazen.Test.WebP\bin\Release\Imazen.Test.Webp.dll /appveyor
#  - xunit.console.clr4.x86.exe Imazen.Test.WebP\bin\Release\Imazen.Test.Webp.dll /appveyor
