clone_depth: 1
version: 4.0.0.{build}

environment:
  fb_nuget_url: https://www.myget.org/F/test-test-test/
  fb_nuget_key:
    secure: GmqIvIvIOiwNxjW+z+vL9tbVD9vqUdB+0HsdDhnhR3km4WLZwpLcQT41D7xlhgFX
  
  fb_s3_bucket: imazen-test
  fb_s3_id:
    secure: Qi7mSLHr94NfJaH0CzQSVPEl1peaOoJADyfHwiVtJzo=
  fb_s3_key:
    secure: RP9hZqS0Pt2SLeias0iZpt2E9OltVX8OPfhWnGET6fQKZ05Fy6y0z1JcWWvONhF0

before_build:
  - git submodule init
  - git submodule update
  
  - nuget restore Core\ImageResizer.sln
  - nuget Install FAKE -ExcludeVersion
  - nuget Install SharpZipLib -ExcludeVersion

build_script:
  - cd Tools
  - ..\packages\FAKE\tools\Fake FakeBuilder\build.fsx
  - cd ..

test: off
