clone_depth: 1
version: 4.0.0.{build}

environment:
  fb_nuget_url: https://www.myget.org/F/test-test-test/
  fb_nuget_key:
    secure: GmqIvIvIOiwNxjW+z+vL9tbVD9vqUdB+0HsdDhnhR3km4WLZwpLcQT41D7xlhgFX
  
  #ab_s3_bucket: imazen-test
  #ab_s3_id:
  #  secure: Qi7mSLHr94NfJaH0CzQSVPEl1peaOoJADyfHwiVtJzo=
  #ab_s3_key:
  #  secure: RP9hZqS0Pt2SLeias0iZpt2E9OltVX8OPfhWnGET6fQKZ05Fy6y0z1JcWWvONhF0

before_build:
  - curl -L -o Tools\nuget.exe http://www.nuget.org/nuget.exe > nul 2>&1
  
  - cd submodules
  - rmdir libwebp-net
  - git clone https://github.com/imazen/libwebp-net --depth 1
  - cd ..
  
  - nuget restore Core\ImageResizer.sln
  - nuget Install FAKE -ExcludeVersion

build_script:
  - cd Tools
  - ..\packages\FAKE\tools\Fake FakeBuilder\build.fsx
  - cd ..
