os: Windows Server 2012 R2

clone_depth: 1
version: 4.0.0.{build}

services:
  - mssql2012sp1

environment:
  fb_nuget_url: https://www.myget.org/F/test-test-test/
  fb_nuget_key:
    secure: GmqIvIvIOiwNxjW+z+vL9tbVD9vqUdB+0HsdDhnhR3km4WLZwpLcQT41D7xlhgFX
  
  fb_s3_bucket: imazen-test
  fb_s3_id:
    secure: Qi7mSLHr94NfJaH0CzQSVPEl1peaOoJADyfHwiVtJzo=
  fb_s3_key:
    secure: RP9hZqS0Pt2SLeias0iZpt2E9OltVX8OPfhWnGET6fQKZ05Fy6y0z1JcWWvONhF0
  
  fb_pub_url: https://s3.amazonaws.com/imazen-test

before_build:
  - ps: md $env:temp\mongo\data
  - ps: Push-Location $env:temp\mongo
  - ps: Invoke-WebRequest https://s3.amazonaws.com/public-unit-test-resources/mongodb/mongod.exe.zip -OutFile mongodb.zip
  - 7z x -o.\ mongodb.zip
  - mongod.exe --logpath=mongo.log --dbpath=. --smallfiles --install
  - ps: Start-Sleep -Seconds 5
  - ps: net start mongodb
  - ps: Pop-Location

build_script:
  - cd Tools
  - builder update
  - builder do_all
  - cd ..

test: off
